### ISSUE TITLE
Create a quick and dirty webpage for this group

### ISSUE THREAD

**Issue by BinRoot** [conversational-interfaces/conversational-interfaces.github.io#1]

**Comment by davidburden103** [comment]
Agreed. Would be good to get a simple list of what may be in our out of scope on that, and links to related standards etc

**Comment by BinRoot** [comment]
To get the ball rolling, I put up a page with minimalist CSS from https://github.com/egoist/hack 

So far the page includes:
- ability to join the CG
- small intro to what the CG does
- link to charter
- peek into the contributions we're making

As you mentioned, a couple more sections would make it feel more complete for now:
- links to related standards (AIML, Behavior Markup Language, ChatScript, RiveScript, etc.) 
- timeline, roadmap
- upcoming events, such as meetings, and links to minutes

**Comment by BinRoot** [comment]
Website now redirects to wiki
